In [202]:
import blackbox
import tp_code
import numpy as np

Question 1. 


on intercepte ,?jtajY.tcrL0tvtl?20.Y

Y est la 51ème lettre de la liste devient (,) qui est 65ème

donc on a 50*(k1)+k2 mod 67 = 64 

o qui est le 15ème caractère devient (?) qui est le 66ème

donc on a 14*(k1) + k2 mod 67 = 65

On résout le systeme on a k1=13
donc k2 = 17

et on trouve le message en inversant le cipher



In [201]:
s = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,?!"
n = len(s)
c=",?jtajY.tcrL0tvtl?20.Y"
k1=13
k2=(64-50*k1)%n

def weakDecipher1(ciphertext: str, k1: int, k2: int):
    s = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,?!"
    n = len(s)
    res = ""
    k1_inv = pow(k1, -1, n)#Merci au "à toute fins utiles"
    for c in ciphertext:
        pos = s.find(c)
        if pos >= 0:
            pos = (k1_inv * (pos - k2)) % n
            res += s[pos]
        else:
            raise ValueError("Unrecognized character: '%s'" % str(c))
    return res

print(weakDecipher1(c, k1, k2))


You just earn 5 points


Question 2. 

On peut retrouver les k0, k1, k2 grâce à notre chiffré

on a : 

$$
\begin{pmatrix}
T & h & 1\\
i & s & 1\\
s & ! & 1
\end{pmatrix}

\cdot

\begin{pmatrix}
k_0\\
k_1\\
k_2
\end{pmatrix}

=

\begin{pmatrix}
j\\
Y\\
C
\end{pmatrix}
$$
et pareillement

$$
\begin{pmatrix}
T & h & 1\\
i & s & 1\\
s & ! & 1
\end{pmatrix}

\cdot

\begin{pmatrix}
k_3\\
k_4\\
k_5
\end{pmatrix}

=

\begin{pmatrix}
5\\
T\\
c
\end{pmatrix}

$$


En resolvant on trouve : 

(47, 40, 26)
(17, 50, 14)

Ou bien si on part du principe qu'on a rajouté un point parce que le message était impair

(13, 17, 42)
(0, 5, 22)

In [200]:
X=matrix(Zmod(67),[[s.find("T"), s.find("h"), 1], [s.find("i"), s.find("s"), 1], [s.find("!"), s.find("."), 1]])
print(X)
Y1=vector(Zmod(67),[s.find("j"), s.find("Y"), s.find("C")])
Y2=vector(Zmod(67),[s.find("5"), s.find("T"), s.find("c")])
Xinv=X.inverse()
k0k1k2=Xinv * Y1
k3k4k5=Xinv * Y2
print(k0k1k2)
print(k3k4k5)



[45  7  1]
[ 8 18  1]
[66 63  1]
(13, 17, 42)
(0, 5, 22)


On fait pareil de l'algébre pour trouver 

$$
\begin{pmatrix}
x_1\\
x_2
\end{pmatrix}

=

\begin{pmatrix}
k_0 & k_1\\
k_3 & k_4
\end{pmatrix}
^{-1}

\cdot

\begin{pmatrix}
y_1 - k_2\\
y_2 - k_5
\end{pmatrix}
$$

In [199]:

def weakDecipher2(ciphertext, key):
    if len(key) != 6:
        raise ValueError("Expected a list of length 6 (of integers)")
    s = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,?!"
    n = len(s)
    if (len(ciphertext) % 2 != 0):
        ciphertext += "."
    keymatrix=matrix(Zmod(67), [[key[0], key[1]], [key[3], key[4]]]) #la matrice par quoi on multiplie
    decalage=vector(Zmod(67), [key[2], key[5]])#les clés par lesquelles on
    res = ""
    keymatrix_inv = keymatrix.inverse()
    for i in range(0, len(ciphertext), 2):
        y1 = s.find(ciphertext[i])
        y2 = s.find(ciphertext[i+1])
        y = vector(Zmod(67), [y1, y2])
        x = keymatrix_inv * (y - decalage)
        res += s[int(x[0])] + s[int(x[1])]
    return res
key=[47, 40, 26,17, 50, 14]
key_bis=[13, 17, 42, 0, 5, 22]
message = weakDecipher2(tp_code.q2_challenge, key)
messagebis = weakDecipher2(tp_code.q2_challenge, key_bis)
print(message)
print(messagebis)



ThisAv!I7iNplHY7xyiF3kAvieiylgVL!PghG3VeOkQyKADjzAuR3F0 s!
This challenge is more complicated, so you got 10 points!.


Question 3. 

On refait pareil mais avec : 

$$
\begin{pmatrix}
c & h & 1\\
a & l & 1\\
l & e & 1
\end{pmatrix}
$$

ptet c'est pas comme ça mais :

$$
\begin{pmatrix}
h & a & 1\\
l & l & 1\\
e & n & 1
\end{pmatrix}
$$

c'est comme ça

In [198]:
X=matrix(Zmod(67),[[s.find("h"), s.find("a"), 1], [s.find("l"), s.find("l"), 1], [s.find("e"), s.find("n"), 1]])
#super piège....
print(X)
c=tp_code.q3_challenge
Xinv=X.inverse()
i=0
message=""
while "challenge" not in message:
    Y1=vector(Zmod(67),[s.find(c[i]), s.find(c[i+2]), s.find(c[i+4])])
    Y2=vector(Zmod(67),[s.find(c[i+1]), s.find(c[i+3]), s.find(c[i+5])])
    k0k1k2=Xinv * Y1
    k3k4k5=Xinv * Y2 
    key=[int(k0k1k2[0]), int(k0k1k2[1]), int(k0k1k2[2]), int(k3k4k5[0]), int(k3k4k5[1]), int(k3k4k5[2])]   
    keymatrix=matrix(Zmod(67), [[key[0], key[1]], [key[3], key[4]]]) #la matrice par quoi on multiplie
    if keymatrix.is_invertible():
        message = weakDecipher2(c, key)
    i=i+1
print(message)

[ 7  0  1]
[11 11  1]
[ 4 13  1]
Well done, you completed all the challenges, you obtain 5 more points!


Question 4.



In [205]:
message=[]
for i in range(16):
    n=len(s)
    r=randint(0, 255)   
    message.append(r)
c1=blackbox.weakCipher3(message)
messagebis=message
print(f"message 1: {message}")

messagebis[5]=randint(0, 255)
print(f"messagebis: {messagebis}")
c2=blackbox.weakCipher3(messagebis)
print(f"c1: {c1}")
print(f"c2: {c2}")
#On voit que changer le i-ème caractère du message change le n-ième caractère du ciphertext.
print(tp_code.q4_challenge)
ciphertext = tp_code.base64_decode(tp_code.q4_challenge)
print(ciphertext)
ciphertext_bis = ciphertext[::-1]
print(ciphertext_bis)





    

message 1: [89, 163, 107, 61, 191, 12, 83, 90, 28, 37, 161, 107, 178, 154, 200, 45]
messagebis: [89, 163, 107, 61, 191, 251, 83, 90, 28, 37, 161, 107, 178, 154, 200, 45]
c1: [113, 208, 58, 203, 249, 98, 178, 250, 174, 234, 136, 1, 180, 252, 147, 76]
c2: [113, 208, 58, 203, 249, 98, 178, 250, 174, 234, 136, 187, 180, 252, 147, 76]
9GVHL2Jb+QLfityW1Umw5w==
[244, 101, 71, 47, 98, 91, 249, 2, 223, 138, 220, 150, 213, 73, 176, 231]
[231, 176, 73, 213, 150, 220, 138, 223, 2, 249, 91, 98, 47, 71, 101, 244]
